apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-root
  labels:
    name: service-root
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: service-root
              port: 
                number: 80
